namespace Innovayse.Infrastructure.Branding;

using Innovayse.Application.Admin.Common;
using Innovayse.Application.Admin.Interfaces;
using Innovayse.Infrastructure.Branding.Options;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

/// <summary>
/// Writes rendered branding files under the web root and reports their URLs.
/// </summary>
/// <remarks>
/// <para>
/// <b>Each upload gets its own directory, named by a fresh identifier.</b> A new logo therefore
/// never overwrites the previous one. Two reasons, and the second is the one that bites: a
/// browser and every proxy in front of it cache <c>/uploads/branding/logo.png</c> aggressively,
/// so overwriting in place ships an operator a stale logo they cannot clear; and until the
/// setting row is updated the old files are still the live ones, so overwriting would swap the
/// storefront's logo before the operator pressed Save.
/// </para>
/// <para>
/// The cost is that superseded uploads are left on disk. That is deliberate for now -- they are
/// small, and deleting the previous set would break exactly the roll-back the separate
/// directories exist to allow. A deployment that accumulates enough of them wants a sweep of
/// directories no setting references, which is a scheduled job rather than something an upload
/// should do inline.
/// </para>
/// </remarks>
/// <param name="env">Host environment, for locating the web root.</param>
/// <param name="options">Branding paths and ceilings.</param>
/// <param name="logger">Log sink.</param>
public sealed class FileSystemBrandingStorage(
    IWebHostEnvironment env,
    IOptions<BrandingOptions> options,
    ILogger<FileSystemBrandingStorage> logger) : IBrandingStorage
{
    /// <summary>Resolved branding paths and ceilings.</summary>
    private readonly BrandingOptions _options = options.Value;

    /// <inheritdoc />
    public async Task<IReadOnlyList<BrandingAssetDto>> SaveAsync(
        BrandingKind kind,
        IReadOnlyList<BrandingRendition> renditions,
        CancellationToken ct)
    {
        var webRoot = env.WebRootPath ?? Path.Combine(env.ContentRootPath, "wwwroot");
        var uploadsRoot = Path.GetFullPath(Path.Combine(webRoot, _options.RelativePath));

        // "logo" / "favicon" come from an enum, not from the request, so this segment cannot be
        // steered by a caller.
        var kindSegment = kind.ToString().ToLowerInvariant();
        var uploadId = Guid.NewGuid().ToString("n");

        var targetDir = Path.Combine(uploadsRoot, kindSegment, uploadId);
        Directory.CreateDirectory(targetDir);

        var assets = new List<BrandingAssetDto>(renditions.Count);

        foreach (var rendition in renditions)
        {
            ct.ThrowIfCancellationRequested();

            var fileName = SafeFileName(rendition.FileName);
            var filePath = Path.Combine(targetDir, fileName);

            // Defence in depth. Every name here is generated by the processor, so this cannot
            // currently fail -- which is the point: if a future change ever lets an uploaded name
            // reach this method, the write is refused rather than landing outside the uploads
            // root. A guard that only matters after someone else's mistake has to be here, not
            // in the caller that is trusted today.
            var resolved = Path.GetFullPath(filePath);
            if (!resolved.StartsWith(uploadsRoot + Path.DirectorySeparatorChar, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    $"Refusing to write branding file outside the uploads root: {rendition.FileName}");
            }

            await File.WriteAllBytesAsync(resolved, rendition.Content, ct);

            // Always forward slashes: this is a URL path, and Path.Combine would produce
            // backslashes on Windows that a browser reads as literal characters.
            var url = $"/{_options.RelativePath.Trim('/')}/{kindSegment}/{uploadId}/{fileName}";

            assets.Add(new BrandingAssetDto(url, rendition.ContentType, rendition.PixelSize, rendition.Role));
        }

        logger.LogInformation(
            "Stored {Count} {Kind} branding file(s) under {Directory}.",
            assets.Count, kindSegment, targetDir);

        return assets;
    }

    /// <summary>
    /// Reduces a rendition name to a bare filename.
    /// </summary>
    /// <param name="fileName">The name the processor chose.</param>
    /// <returns>The name with any directory component removed.</returns>
    /// <exception cref="InvalidOperationException">The name is empty or has no usable part.</exception>
    private static string SafeFileName(string fileName)
    {
        var bare = Path.GetFileName(fileName);

        return string.IsNullOrWhiteSpace(bare) || bare is "." or ".."
            ? throw new InvalidOperationException($"Unusable branding file name: '{fileName}'.")
            : bare;
    }
}
