namespace Innovayse.Domain.Email;

using Innovayse.Domain.Common;
using Innovayse.Domain.Email.Events;

/// <summary>
/// Aggregate root representing a business email domain provisioned through Mailcow.
/// Owns collections of <see cref="Mailbox"/> and <see cref="MailAlias"/> entities.
/// </summary>
public sealed class EmailDomain : AggregateRoot
{
    /// <summary>Internal mutable list of mailboxes belonging to this email domain.</summary>
    private readonly List<Mailbox> _mailboxes = [];

    /// <summary>Internal mutable list of mail aliases belonging to this email domain.</summary>
    private readonly List<MailAlias> _aliases = [];

    /// <summary>Gets the FK to the owning client.</summary>
    public int ClientId { get; private set; }

    /// <summary>Gets the fully-qualified domain name (e.g. "example.com").</summary>
    public string DomainName { get; private set; } = null!;

    /// <summary>Gets the FK to a <c>Domain</c> entity if this domain is managed by the hostpanel.</summary>
    public int? HostpanelDomainId { get; private set; }

    /// <summary>Gets the current lifecycle status.</summary>
    public EmailDomainStatus Status { get; private set; }

    /// <summary>Gets the Mailcow domain identifier; set after provisioning.</summary>
    public string? MailcowRef { get; private set; }

    /// <summary>Gets the DKIM selector used for this domain.</summary>
    public string DkimSelector { get; private set; } = "dkim";

    /// <summary>Gets the DKIM public key; set after Mailcow generates it.</summary>
    public string? DkimPublicKey { get; private set; }

    /// <summary>Gets the maximum number of mailboxes allowed on this domain.</summary>
    public int MaxMailboxes { get; private set; }

    /// <summary>Gets the maximum number of aliases allowed on this domain.</summary>
    public int MaxAliases { get; private set; }

    /// <summary>Gets the maximum total quota in megabytes for this domain.</summary>
    public int MaxQuotaMb { get; private set; }

    /// <summary>Gets the UTC timestamp when DNS was last successfully verified; null until verified.</summary>
    public DateTimeOffset? DnsVerifiedAt { get; private set; }

    /// <summary>Gets the last DNS verification results as JSON; null until first verification attempt.</summary>
    public string? LastDnsVerificationJson { get; private set; }

    /// <summary>Gets the UTC timestamp when this email domain was created.</summary>
    public DateTimeOffset CreatedAt { get; private set; }

    /// <summary>Gets the read-only view of mailboxes belonging to this email domain.</summary>
    public IReadOnlyList<Mailbox> Mailboxes => _mailboxes.AsReadOnly();

    /// <summary>Gets the read-only view of mail aliases belonging to this email domain.</summary>
    public IReadOnlyList<MailAlias> Aliases => _aliases.AsReadOnly();

    /// <summary>EF Core parameterless constructor — do not call directly.</summary>
    private EmailDomain() : base(0) { }

    /// <summary>
    /// Creates a new email domain in <see cref="EmailDomainStatus.PendingDns"/> status
    /// and raises <see cref="EmailDomainCreatedEvent"/>.
    /// </summary>
    /// <param name="clientId">FK to the client requesting the email domain.</param>
    /// <param name="domainName">Fully-qualified domain name for email (e.g. "example.com").</param>
    /// <param name="maxMailboxes">Maximum number of mailboxes allowed.</param>
    /// <param name="maxAliases">Maximum number of aliases allowed.</param>
    /// <param name="maxQuotaMb">Maximum total quota in megabytes.</param>
    /// <param name="hostpanelDomainId">FK to a hostpanel-managed domain, if applicable.</param>
    /// <returns>A new <see cref="EmailDomain"/> in <see cref="EmailDomainStatus.PendingDns"/> state.</returns>
    public static EmailDomain Create(
        int clientId,
        string domainName,
        int maxMailboxes,
        int maxAliases,
        int maxQuotaMb,
        int? hostpanelDomainId = null)
    {
        var emailDomain = new EmailDomain
        {
            ClientId = clientId,
            DomainName = domainName.ToLowerInvariant().Trim(),
            HostpanelDomainId = hostpanelDomainId,
            Status = EmailDomainStatus.PendingDns,
            MaxMailboxes = maxMailboxes,
            MaxAliases = maxAliases,
            MaxQuotaMb = maxQuotaMb,
            CreatedAt = DateTimeOffset.UtcNow,
        };

        emailDomain.AddDomainEvent(
            new EmailDomainCreatedEvent(emailDomain.Id, clientId, emailDomain.DomainName));

        return emailDomain;
    }

    /// <summary>
    /// Records the Mailcow domain reference returned after provisioning.
    /// </summary>
    /// <param name="mailcowRef">Mailcow domain identifier.</param>
    public void SetMailcowRef(string mailcowRef) => MailcowRef = mailcowRef;

    /// <summary>
    /// Records the DKIM public key generated by Mailcow.
    /// Resets the DKIM selector to "dkim".
    /// </summary>
    /// <param name="publicKey">The DKIM public key string.</param>
    public void SetDkimPublicKey(string publicKey)
    {
        DkimSelector = "dkim";
        DkimPublicKey = publicKey;
    }

    /// <summary>
    /// Transitions the domain from <see cref="EmailDomainStatus.PendingDns"/> to
    /// <see cref="EmailDomainStatus.Active"/> and raises <see cref="EmailDomainActivatedEvent"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// Thrown when the domain is not in <see cref="EmailDomainStatus.PendingDns"/> status.
    /// </exception>
    public void Activate()
    {
        if (Status != EmailDomainStatus.PendingDns)
        {
            throw new InvalidOperationException(
                $"Cannot activate email domain in {Status} state.");
        }

        Status = EmailDomainStatus.Active;
        DnsVerifiedAt = DateTimeOffset.UtcNow;

        AddDomainEvent(new EmailDomainActivatedEvent(Id, ClientId, DomainName));
    }

    /// <summary>Stores the last DNS verification results as serialized JSON.</summary>
    public void SetLastDnsVerification(string json) => LastDnsVerificationJson = json;

    /// <summary>Suspends the email domain.</summary>
    public void Suspend() => Status = EmailDomainStatus.Suspended;

    /// <summary>Reactivates a suspended email domain.</summary>
    public void Unsuspend() => Status = EmailDomainStatus.Active;

    /// <summary>
    /// Adds a new mailbox to this email domain.
    /// </summary>
    /// <param name="localPart">Local part of the email address (e.g. "john").</param>
    /// <param name="displayName">Display name for the mailbox owner.</param>
    /// <param name="quotaMb">Storage quota in megabytes.</param>
    /// <returns>The newly created <see cref="Mailbox"/>.</returns>
    /// <exception cref="InvalidOperationException">
    /// Thrown when the domain is not active, the mailbox limit is reached, or the local part already exists.
    /// </exception>
    public Mailbox AddMailbox(string localPart, string displayName, int quotaMb)
    {
        if (Status != EmailDomainStatus.Active)
        {
            throw new InvalidOperationException("Email domain must be active to add mailboxes.");
        }

        if (_mailboxes.Count >= MaxMailboxes)
        {
            throw new InvalidOperationException(
                $"Maximum mailbox limit ({MaxMailboxes}) reached.");
        }

        if (_mailboxes.Any(m => m.LocalPart == localPart.ToLowerInvariant().Trim()))
        {
            throw new InvalidOperationException(
                $"Mailbox '{localPart}@{DomainName}' already exists.");
        }

        var mailbox = Mailbox.Create(Id, localPart, displayName, quotaMb);
        _mailboxes.Add(mailbox);
        return mailbox;
    }

    /// <summary>
    /// Removes a mailbox from this email domain by its ID.
    /// </summary>
    /// <param name="mailboxId">The ID of the mailbox to remove.</param>
    /// <exception cref="InvalidOperationException">Thrown when no mailbox with the given ID exists.</exception>
    public void RemoveMailbox(int mailboxId)
    {
        var mailbox = _mailboxes.FirstOrDefault(m => m.Id == mailboxId)
            ?? throw new InvalidOperationException($"Mailbox {mailboxId} not found.");
        _mailboxes.Remove(mailbox);
    }

    /// <summary>
    /// Adds a new mail alias to this email domain.
    /// </summary>
    /// <param name="source">Source email address (e.g. "info@example.com").</param>
    /// <param name="destination">Destination email address (e.g. "john@example.com").</param>
    /// <returns>The newly created <see cref="MailAlias"/>.</returns>
    /// <exception cref="InvalidOperationException">
    /// Thrown when the domain is not active or the alias limit is reached.
    /// </exception>
    public MailAlias AddAlias(string source, string destination)
    {
        if (Status != EmailDomainStatus.Active)
        {
            throw new InvalidOperationException("Email domain must be active to add aliases.");
        }

        if (_aliases.Count >= MaxAliases)
        {
            throw new InvalidOperationException(
                $"Maximum alias limit ({MaxAliases}) reached.");
        }

        var alias = MailAlias.Create(Id, source, destination);
        _aliases.Add(alias);
        return alias;
    }

    /// <summary>
    /// Removes a mail alias from this email domain by its ID.
    /// </summary>
    /// <param name="aliasId">The ID of the alias to remove.</param>
    /// <exception cref="InvalidOperationException">Thrown when no alias with the given ID exists.</exception>
    public void RemoveAlias(int aliasId)
    {
        var alias = _aliases.FirstOrDefault(a => a.Id == aliasId)
            ?? throw new InvalidOperationException($"Alias {aliasId} not found.");
        _aliases.Remove(alias);
    }
}
