/**
 * GET /api/portal/client/services/:id/cpanel-sso
 *
 * Returns `{ url }`: a one-time control-panel sign-in address, generated by the C# backend.
 *
 * The backend used to answer with the URL as a bare JSON string while this route declared
 * `{ url: string }`, so the page's `const { url } = ...` read `undefined` off a string and
 * opened a blank tab with it. `MyServicesController` now answers with the object its staff-side
 * sibling always did, which is the shape declared here.
 */
export default defineEventHandler(async (event) => {
  const id = getRouterParam(event, 'id')
  if (!id) throw createError({ statusCode: 400, statusMessage: 'Service ID is required' })

  return await internalApiCall<{ url: string }>(event, `/me/services/${id}/cpanel-sso`)
})
