namespace Innovayse.Application.Common;

/// <summary>
/// DTO representing a country with its ISO 3166-1 alpha-2 code and English name.
/// </summary>
/// <param name="Code">ISO 3166-1 alpha-2 two-letter country code (e.g. "US").</param>
/// <param name="Name">English name of the country (e.g. "United States").</param>
public record CountryDto(string Code, string Name);

/// <summary>
/// Static reference list of all 249 ISO 3166-1 alpha-2 countries.
/// Used by the admin UI for country selection dropdowns.
/// </summary>
public static class CountryList
{
    /// <summary>All ISO 3166-1 alpha-2 countries, sorted by code.</summary>
    public static readonly IReadOnlyList<CountryDto> All =
    [
        new("AD", "Andorra"),
        new("AE", "United Arab Emirates"),
        new("AF", "Afghanistan"),
        new("AG", "Antigua and Barbuda"),
        new("AI", "Anguilla"),
        new("AL", "Albania"),
        new("AM", "Armenia"),
        new("AO", "Angola"),
        new("AQ", "Antarctica"),
        new("AR", "Argentina"),
        new("AS", "American Samoa"),
        new("AT", "Austria"),
        new("AU", "Australia"),
        new("AW", "Aruba"),
        new("AX", "Aland Islands"),
        new("AZ", "Azerbaijan"),
        new("BA", "Bosnia and Herzegovina"),
        new("BB", "Barbados"),
        new("BD", "Bangladesh"),
        new("BE", "Belgium"),
        new("BF", "Burkina Faso"),
        new("BG", "Bulgaria"),
        new("BH", "Bahrain"),
        new("BI", "Burundi"),
        new("BJ", "Benin"),
        new("BL", "Saint Barthelemy"),
        new("BM", "Bermuda"),
        new("BN", "Brunei Darussalam"),
        new("BO", "Bolivia"),
        new("BQ", "Bonaire, Sint Eustatius and Saba"),
        new("BR", "Brazil"),
        new("BS", "Bahamas"),
        new("BT", "Bhutan"),
        new("BV", "Bouvet Island"),
        new("BW", "Botswana"),
        new("BY", "Belarus"),
        new("BZ", "Belize"),
        new("CA", "Canada"),
        new("CC", "Cocos (Keeling) Islands"),
        new("CD", "Congo, Democratic Republic of the"),
        new("CF", "Central African Republic"),
        new("CG", "Congo"),
        new("CH", "Switzerland"),
        new("CI", "Cote d'Ivoire"),
        new("CK", "Cook Islands"),
        new("CL", "Chile"),
        new("CM", "Cameroon"),
        new("CN", "China"),
        new("CO", "Colombia"),
        new("CR", "Costa Rica"),
        new("CU", "Cuba"),
        new("CV", "Cabo Verde"),
        new("CW", "Curacao"),
        new("CX", "Christmas Island"),
        new("CY", "Cyprus"),
        new("CZ", "Czechia"),
        new("DE", "Germany"),
        new("DJ", "Djibouti"),
        new("DK", "Denmark"),
        new("DM", "Dominica"),
        new("DO", "Dominican Republic"),
        new("DZ", "Algeria"),
        new("EC", "Ecuador"),
        new("EE", "Estonia"),
        new("EG", "Egypt"),
        new("EH", "Western Sahara"),
        new("ER", "Eritrea"),
        new("ES", "Spain"),
        new("ET", "Ethiopia"),
        new("FI", "Finland"),
        new("FJ", "Fiji"),
        new("FK", "Falkland Islands (Malvinas)"),
        new("FM", "Micronesia, Federated States of"),
        new("FO", "Faroe Islands"),
        new("FR", "France"),
        new("GA", "Gabon"),
        new("GB", "United Kingdom"),
        new("GD", "Grenada"),
        new("GE", "Georgia"),
        new("GF", "French Guiana"),
        new("GG", "Guernsey"),
        new("GH", "Ghana"),
        new("GI", "Gibraltar"),
        new("GL", "Greenland"),
        new("GM", "Gambia"),
        new("GN", "Guinea"),
        new("GP", "Guadeloupe"),
        new("GQ", "Equatorial Guinea"),
        new("GR", "Greece"),
        new("GS", "South Georgia and the South Sandwich Islands"),
        new("GT", "Guatemala"),
        new("GU", "Guam"),
        new("GW", "Guinea-Bissau"),
        new("GY", "Guyana"),
        new("HK", "Hong Kong"),
        new("HM", "Heard Island and McDonald Islands"),
        new("HN", "Honduras"),
        new("HR", "Croatia"),
        new("HT", "Haiti"),
        new("HU", "Hungary"),
        new("ID", "Indonesia"),
        new("IE", "Ireland"),
        new("IL", "Israel"),
        new("IM", "Isle of Man"),
        new("IN", "India"),
        new("IO", "British Indian Ocean Territory"),
        new("IQ", "Iraq"),
        new("IR", "Iran, Islamic Republic of"),
        new("IS", "Iceland"),
        new("IT", "Italy"),
        new("JE", "Jersey"),
        new("JM", "Jamaica"),
        new("JO", "Jordan"),
        new("JP", "Japan"),
        new("KE", "Kenya"),
        new("KG", "Kyrgyzstan"),
        new("KH", "Cambodia"),
        new("KI", "Kiribati"),
        new("KM", "Comoros"),
        new("KN", "Saint Kitts and Nevis"),
        new("KP", "Korea, Democratic People's Republic of"),
        new("KR", "Korea, Republic of"),
        new("KW", "Kuwait"),
        new("KY", "Cayman Islands"),
        new("KZ", "Kazakhstan"),
        new("LA", "Lao People's Democratic Republic"),
        new("LB", "Lebanon"),
        new("LC", "Saint Lucia"),
        new("LI", "Liechtenstein"),
        new("LK", "Sri Lanka"),
        new("LR", "Liberia"),
        new("LS", "Lesotho"),
        new("LT", "Lithuania"),
        new("LU", "Luxembourg"),
        new("LV", "Latvia"),
        new("LY", "Libya"),
        new("MA", "Morocco"),
        new("MC", "Monaco"),
        new("MD", "Moldova, Republic of"),
        new("ME", "Montenegro"),
        new("MF", "Saint Martin (French part)"),
        new("MG", "Madagascar"),
        new("MH", "Marshall Islands"),
        new("MK", "North Macedonia"),
        new("ML", "Mali"),
        new("MM", "Myanmar"),
        new("MN", "Mongolia"),
        new("MO", "Macao"),
        new("MP", "Northern Mariana Islands"),
        new("MQ", "Martinique"),
        new("MR", "Mauritania"),
        new("MS", "Montserrat"),
        new("MT", "Malta"),
        new("MU", "Mauritius"),
        new("MV", "Maldives"),
        new("MW", "Malawi"),
        new("MX", "Mexico"),
        new("MY", "Malaysia"),
        new("MZ", "Mozambique"),
        new("NA", "Namibia"),
        new("NC", "New Caledonia"),
        new("NE", "Niger"),
        new("NF", "Norfolk Island"),
        new("NG", "Nigeria"),
        new("NI", "Nicaragua"),
        new("NL", "Netherlands"),
        new("NO", "Norway"),
        new("NP", "Nepal"),
        new("NR", "Nauru"),
        new("NU", "Niue"),
        new("NZ", "New Zealand"),
        new("OM", "Oman"),
        new("PA", "Panama"),
        new("PE", "Peru"),
        new("PF", "French Polynesia"),
        new("PG", "Papua New Guinea"),
        new("PH", "Philippines"),
        new("PK", "Pakistan"),
        new("PL", "Poland"),
        new("PM", "Saint Pierre and Miquelon"),
        new("PN", "Pitcairn"),
        new("PR", "Puerto Rico"),
        new("PS", "Palestine, State of"),
        new("PT", "Portugal"),
        new("PW", "Palau"),
        new("PY", "Paraguay"),
        new("QA", "Qatar"),
        new("RE", "Reunion"),
        new("RO", "Romania"),
        new("RS", "Serbia"),
        new("RU", "Russian Federation"),
        new("RW", "Rwanda"),
        new("SA", "Saudi Arabia"),
        new("SB", "Solomon Islands"),
        new("SC", "Seychelles"),
        new("SD", "Sudan"),
        new("SE", "Sweden"),
        new("SG", "Singapore"),
        new("SH", "Saint Helena, Ascension and Tristan da Cunha"),
        new("SI", "Slovenia"),
        new("SJ", "Svalbard and Jan Mayen"),
        new("SK", "Slovakia"),
        new("SL", "Sierra Leone"),
        new("SM", "San Marino"),
        new("SN", "Senegal"),
        new("SO", "Somalia"),
        new("SR", "Suriname"),
        new("SS", "South Sudan"),
        new("ST", "Sao Tome and Principe"),
        new("SV", "El Salvador"),
        new("SX", "Sint Maarten (Dutch part)"),
        new("SY", "Syrian Arab Republic"),
        new("SZ", "Eswatini"),
        new("TC", "Turks and Caicos Islands"),
        new("TD", "Chad"),
        new("TF", "French Southern Territories"),
        new("TG", "Togo"),
        new("TH", "Thailand"),
        new("TJ", "Tajikistan"),
        new("TK", "Tokelau"),
        new("TL", "Timor-Leste"),
        new("TM", "Turkmenistan"),
        new("TN", "Tunisia"),
        new("TO", "Tonga"),
        new("TR", "Turkey"),
        new("TT", "Trinidad and Tobago"),
        new("TV", "Tuvalu"),
        new("TW", "Taiwan, Province of China"),
        new("TZ", "Tanzania, United Republic of"),
        new("UA", "Ukraine"),
        new("UG", "Uganda"),
        new("UM", "United States Minor Outlying Islands"),
        new("US", "United States"),
        new("UY", "Uruguay"),
        new("UZ", "Uzbekistan"),
        new("VA", "Holy See (Vatican City State)"),
        new("VC", "Saint Vincent and the Grenadines"),
        new("VE", "Venezuela, Bolivarian Republic of"),
        new("VG", "Virgin Islands, British"),
        new("VI", "Virgin Islands, U.S."),
        new("VN", "Viet Nam"),
        new("VU", "Vanuatu"),
        new("WF", "Wallis and Futuna"),
        new("WS", "Samoa"),
        new("YE", "Yemen"),
        new("YT", "Mayotte"),
        new("ZA", "South Africa"),
        new("ZM", "Zambia"),
        new("ZW", "Zimbabwe"),
    ];
}
